server:
  port: 18100

spring:
  application:
    name: mysql-kit
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server.year.cn:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
